### ISSUE TITLE
Panic: short record

### ISSUE THREAD

**Issue by jozuenoon** [oklog/oklog#111]
I'm landing in unrecoverable state with following stack trace:

```
panic: short record
 goroutine 85 [running]:
github.com/oklog/oklog/pkg/store.mergeRecords.func1(0x0, 0xc42021550d, 0x22c)
	/home/wk/go/src/github.com/oklog/oklog/pkg/store/read.go:55 +0x25c
github.com/oklog/oklog/pkg/store.mergeRecords(0xaa5840, 0xc420506690, 0xc4203e5a08, 0x1, 0x1, 0xa3be421fb626201, 0x271c65c7a4ee6135, 0x2e7c4d26fb626201, 0x691c061555dc58bb, 0x0, ...)
	/home/wk/go/src/github.com/oklog/oklog/pkg/store/read.go:115 +0x7b1
github.com/oklog/oklog/pkg/store.(*Consumer).gather(0xc420426000, 0x0)
	/home/wk/go/src/github.com/oklog/oklog/pkg/store/consume.go:205 +0x142c
github.com/oklog/oklog/pkg/store.(*Consumer).(github.com/oklog/oklog/pkg/store.gather)-fm(0xc420219ef0)
	/home/wk/go/src/github.com/oklog/oklog/pkg/store/consume.go:78 +0x2a
github.com/oklog/oklog/pkg/store.(*Consumer).Run(0xc420426000)
	/home/wk/go/src/github.com/oklog/oklog/pkg/store/consume.go:82 +0x95
main.runIngestStore.func12(0x0, 0x0)
	/home/wk/go/src/github.com/oklog/oklog/cmd/oklog/ingeststore.go:423 +0x2a
github.com/oklog/oklog/vendor/github.com/oklog/run.(*Group).Run.func1(0xc4204a68a0, 0xc420502330, 0xc420502340)
	/home/wk/go/src/github.com/oklog/oklog/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/oklog/oklog/vendor/github.com/oklog/run.(*Group).Run
	/home/wk/go/src/github.com/oklog/oklog/vendor/github.com/oklog/run/group.go:37 +0xa8
```

any thoughts ?

**Comment by peterbourgon** [comment]
Looks like you've got a bad record saved to disk somehow. Can you go to your store's data dir and `tail -n1` each of the files there? I bet one of them will have a truncated ULID.

**Comment by jozuenoon** [comment]
I needed to recover quickly so I just wiped out everything... but I will watch against that next time. Maybe if someone else encounter that bug could directly debug it.
