### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by wangkechun** [oklog/oklog#41]
```
ts=2017-02-17T17:03:13.401949521Z level=info cluster=0.0.0.0:7659
ts=2017-02-17T17:03:13.402359566Z level=info fast=tcp://0.0.0.0:7651
ts=2017-02-17T17:03:13.402686896Z level=info durable=tcp://0.0.0.0:7652
ts=2017-02-17T17:03:13.403006829Z level=info bulk=tcp://0.0.0.0:7653
ts=2017-02-17T17:03:13.403323151Z level=info API=tcp://0.0.0.0:7650
ts=2017-02-17T17:03:13.403588199Z level=info ingest_path=data/ingest
ts=2017-02-17T17:03:13.403772636Z level=info store_path=data/store
ts=2017-02-17T17:03:13.405190477Z level=debug component=cluster Join=0
2017/02/18 01:08:14 http: panic serving 127.0.0.1:11723: runtime error: invalid memory address or nil pointer dereference
goroutine 1939 [running]:
net/http.(*conn).serve.func1(0xc42a811040)
	/usr/local/Cellar/go/1.8rc2_2/libexec/src/net/http/server.go:1721 +0xd0
panic(0x8eef80, 0xc0b410)
	/usr/local/Cellar/go/1.8rc2_2/libexec/src/runtime/panic.go:489 +0x2cf
github.com/oklog/oklog/pkg/store.makeConcurrentFilteringReadClosers.func1(0xc42bed3830, 0xc42bed3810)
	/Users/peter/src/github.com/oklog/oklog/pkg/store/query.go:232 +0x57
github.com/oklog/oklog/pkg/store.makeConcurrentFilteringReadClosers(0xbe93e0, 0xc4201b284c, 0xc482cf5580, 0x5, 0x8, 0xc43415df90, 0x100000, 0xc42eb8ea50, 0x5, 0x5, ...)
	/Users/peter/src/github.com/oklog/oklog/pkg/store/query.go:242 +0x2c9
github.com/oklog/oklog/pkg/store.newQueryReadCloser(0xbe93e0, 0xc4201b284c, 0xc424e2a200, 0x1f, 0x20, 0xc43415df90, 0x100000, 0x0, 0x0, 0x9ea4f887, ...)
	/Users/peter/src/github.com/oklog/oklog/pkg/store/query.go:155 +0x44e
github.com/oklog/oklog/pkg/store.(*fileLog).Query(0xc4201b8d40, 0xed03916ed, 0xc400000000, 0xc1a0a0, 0xed03924fd, 0x0, 0xc1a0a0, 0xc482cf5461, 0x10, 0x100, ...)
	/Users/peter/src/github.com/oklog/oklog/pkg/store/file_log.go:104 +0x27e
github.com/oklog/oklog/pkg/store.(*API).handleInternalQuery(0xc4201a4500, 0xbe3f80, 0xc482cf2a40, 0xc43fc7a000, 0xc482cf2a01)
	/Users/peter/src/github.com/oklog/oklog/pkg/store/api.go:195 +0x265
github.com/oklog/oklog/pkg/store.(*API).ServeHTTP(0xc4201a4500, 0xbe4580, 0xc420f7f960, 0xc43fc7a000)
	/Users/peter/src/github.com/oklog/oklog/pkg/store/api.go:68 +0x593
net/http.StripPrefix.func1(0xbe4580, 0xc420f7f960, 0xc43fc7a000)
	/usr/local/Cellar/go/1.8rc2_2/libexec/src/net/http/server.go:1977 +0xcf
net/http.HandlerFunc.ServeHTTP(0xc420268180, 0xbe4580, 0xc420f7f960, 0xc43fc7a000)
	/usr/local/Cellar/go/1.8rc2_2/libexec/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420268000, 0xbe4580, 0xc420f7f960, 0xc43fc7a000)
	/usr/local/Cellar/go/1.8rc2_2/libexec/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc42013ee70, 0xbe4580, 0xc420f7f960, 0xc43fc7a000)
	/usr/local/Cellar/go/1.8rc2_2/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42a811040, 0xbe4fc0, 0xc42031c880)
	/usr/local/Cellar/go/1.8rc2_2/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8rc2_2/libexec/src/net/http/server.go:2668 +0x2ce
```

**Comment by peterbourgon** [comment]
I released https://github.com/oklog/oklog/releases/tag/v0.1.3 for this. Thanks for the report.
