### ISSUE TITLE
store: after panic LOCK file left in place

### ISSUE THREAD

**Issue by newhook** [oklog/oklog#58]
matthew@log-store-1:~$ oklog store -cluster `hostname --ip-address` -peer log-store-1 -peer log-store-2 -peer log-store-3 -peer log-ingest-1 -peer log-ingest-2 -peer log-ingest-3 --store.path=/data/logs
ts=2017-04-06T12:21:04.761341821Z level=info cluster=10.240.0.24:7659
ts=2017-04-06T12:21:04.761668709Z level=info API=tcp://0.0.0.0:7650
ts=2017-04-06T12:21:04.778903484Z level=info StoreLog=/data/logs
ts=2017-04-06T12:21:04.859704498Z level=debug component=cluster Join=1
panic: ulid: bad data size when unmarshaling

goroutine 16 [running]:
github.com/oklog/oklog/vendor/github.com/oklog/ulid.MustParse(0xc420242a8b, 0x8, 0x0, 0x0)
	/Users/pbourgon/src/github.com/oklog/oklog/vendor/github.com/oklog/ulid/ulid.go:98 +0x88
github.com/oklog/oklog/pkg/store.(*fileLog).Overlapping(0xc42016eec0, 0x40, 0x87ae4b, 0xc42003abc8, 0xc42003abc0, 0xc42004cd20)
	/Users/pbourgon/src/github.com/oklog/oklog/pkg/store/file_log.go:157 +0x70b
github.com/oklog/oklog/pkg/store.(Log).Overlapping-fm(0xe00000040, 0xa07ee8, 0xc420059380, 0x9ebd47, 0xb)
	/Users/pbourgon/src/github.com/oklog/oklog/pkg/store/compact.go:48 +0x2f
github.com/oklog/oklog/pkg/store.(*Compacter).compact(0xc420059380, 0x9ebd47, 0xb, 0xc42003adf8, 0x0, 0x0, 0x0)
	/Users/pbourgon/src/github.com/oklog/oklog/pkg/store/compact.go:86 +0xf0
github.com/oklog/oklog/pkg/store.(*Compacter).Run.func1()
	/Users/pbourgon/src/github.com/oklog/oklog/pkg/store/compact.go:48 +0x7a
github.com/oklog/oklog/pkg/store.(*Compacter).Run(0xc420059380)
	/Users/pbourgon/src/github.com/oklog/oklog/pkg/store/compact.go:58 +0x2b1
main.runStore.func7(0x0, 0x0)
	/Users/pbourgon/src/github.com/oklog/oklog/cmd/oklog/store.go:260 +0x2a
github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc420059440, 0xc420013250, 0xc420013260)
	/Users/pbourgon/src/github.com/oklog/oklog/pkg/group/group.go:55 +0x27
created by github.com/oklog/oklog/pkg/group.(*Group).Run
	/Users/pbourgon/src/github.com/oklog/oklog/pkg/group/group.go:56 +0xa8
matthew@log-store-1:~$ oklog store -cluster `hostname --ip-address` -peer log-store-1 -peer log-store-2 -peer log-store-3 -peer log-ingest-1 -peer log-ingest-2 -peer log-ingest-3 --store.path=/data/logs
ts=2017-04-06T12:21:08.870118774Z level=info cluster=10.240.0.24:7659
ts=2017-04-06T12:21:08.870255775Z level=info API=tcp://0.0.0.0:7650
/data/logs/LOCK already exists; another process is running, or the file is stale

**Comment by peterbourgon** [comment]
This is fixed in [v0.2.1](https://github.com/oklog/oklog/releases/tag/v0.2.1), can you upgrade?

**Comment by newhook** [comment]
Can do!

**Comment by peterbourgon** [comment]
Nice.
